parameters:
#    user_user.example.class: User\UserBundle\Example

services:
    user_user.strokit:
        class: User\UserBundle\Services\Munc
        arguments: [@service_container]
#        scope: request
